JelleZijlstra/stubdefaulter

.gitignore
pyproject.toml

This means you can invoke the tool by doing `stubdefaulter [args]` instead of `python -m stubdefaulter [args]`. Also: add `pytest` to the dev-dependencies so it's installed if you do `pip install -e .[dev]` locally.

Add a `project.scripts` section to `pyproject.toml`

---

README.md
stubdefaulter.py

- Skip trying to import `_typeshed` (obviously won't work)
- Skip trying to add defaults for `antigravity` (works, but it's annoying to have the browser open up every time)
- Suppress stdout when importing modules so that there isn't noisy output to the terminal when importing modules like `this`

Skip a few annoying modules when adding defaults to the stdlib

---

.github/workflows/pyanalyze.yml
pyproject.toml

The self-dependency looks a bit weird, but it is apparently explicitly supported (can't find any better docs than this, though): https://discuss.python.org/t/pyproject-toml-optional-dependencies-redundancy-aka-dry-extras/8428/6. I found it somewhat annoying when pyanalyze failed on my PR #16, and I then realised I didn't have pyanalyze installed locally :)

Install pyanalyze when `pip install -e .[dev]` is run

---

pyproject.toml

- Require the latest version of `typeshed_client`
- Bump `flake8-bugbear` to the latest version (matching what's run in CI, since it's unpinned in the pre-commit config). This ensures that you don't get a false-positive error when running flake8 locally (B028 was renamed to B907 in the latest release, but it's still called B028 in release `23.1.14`, meaning the ignore for B907 in the `.flake8` file doesn't work if you run flake8 locally).

Bump typeshed_client and flake8-bugbear pins

---

stubdefaulter.py

This should probably have been part of #20; I realised the oversight in my PR after it was merged

Teach `infer_value_of_node` about float default values in stubs

---

stubdefaulter.py
test_stubdefaulter.py

Nested classes aren't too common in stubs, but we do have a few scattered across typeshed. This change also has the benefit of making the `add_defaults_to_stub` function less complex, which will make changes like #22 less icky to implement.

Handle nested classes properly

---

.pre-commit-config.yaml
pyproject.toml
stubdefaulter.py

This makes it easier to see when things that are definitely errors are being reported, as opposed to things that might be errors (but also might not be)

Colorize output

---

.github/workflows/check.yml
.github/workflows/typeshed_primer.yml

In particular, having the `typeshed_primer` output colorized is useful for identifying at-a-glance why `stubdefaulter` is exiting with code 1 when run as part of the `typeshed_primer` workflow (it's a few troublesome defaults in typeshed's `locale.pyi`).
We may as well also add colors to `pytest` in CI while we're about it :)

Colorize output in CI

---

.pre-commit-config.yaml
pyproject.toml

isort <5.12.0 is incompatible with the latest version of poetry-core, which has been causing many failures in pre-commit across many repos. (See PyCQA/isort#2077 for more details.)

Upgrade to isort 5.12.0

---

stubdefaulter.py

This doesn't affect the total count of defaults which are added to the stdlib (at least not on my machine), but it does slightly reduce the number of 'Could not find <blah> in runtime module' messages that are logged to the terminal

Fall back to `getattr_static` on `AttributeError`

---

stdlib-blacklist.txt

I got
```
multiprocessing.heap.Heap: parameter size: stub default 4096 != runtime default 16384
```

blacklist multiprocessing.heap.Heap

---

stdlib-blacklist.txt

Means I get fewer red error messages when running `stubdefaulter` using Python 3.7

Add two `tkinter` functions to the blacklist

---

stubdefaulter.py
test_stubdefaulter.py

Doesn't make a difference to the defaults added to the stdlib, but it reduces the number of 'Could not find method <blah> at runtime' messages printed to the terminal

Handle methods with mangled names

---

stubdefaulter.py

This has the following effect on output printed to the terminal when running `stubdefaulter` on the stdlib:
```diff
--- a/old.txt
+++ b/new.txt
@@ -768,73 +768,23 @@ Could not find types.GenericAlias.__getattr__ at runtime
added 0 defaults
Processing typing... Could not find typing.type_check_only at runtime
Could not find typing._Alias at runtime
-Could not find typing.Sized.__len__ at runtime
-Could not find typing.Iterable.__iter__ at runtime
-Could not find typing.Iterator.__next__ at runtime
-Could not find typing.Iterator.__iter__ at runtime
-Could not find typing.Reversible.__reversed__ at runtime
-Could not find typing.Generator.__next__ at runtime
-Could not find typing.Generator.__iter__ at runtime
Could not find typing.Generator.gi_code at runtime
Could not find …
```

Add some special casing for typing-module aliases

---

stubdefaulter.py
test_stubdefaulter.py

Unlikely to come up, but hey, it's nice to be correct

Fix some name-mangling edge cases

---

stubdefaulter.py
test_stubdefaulter.py

If the number of parameters in the stub matches the number of parameters at runtime, and there are no variadic parameters at runtime, it should be safe to add defaults to the stub *even if* the stub has an incorrect name for the parameter

Add defaults to pos-only parameters in the stub, even if the parameter name is incorrect in the stub

---

stdlib-blacklist.txt

Stubdefaulter always wants to add defaults to these signatures when I run it on the stdlib stubs using Python 3.7, but the defaults it wants to add look wrong. The `cmath` one is definitely wrong:
```pycon
Python 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmath
>>> help(cmath.log)
Help on built-in function log in module cmath:
log(x, y_obj=None, /)
The logarithm of z to the given base.
If the base not specified, returns the natural logarithm (base e) of z.
>>> cmath.log(5, None)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: must be real number, not NoneType
```
I haven't verified the other two in the same way, but they …

Blacklist a few functions with strange signatures at runtime on py37

---

stdlib-blacklist.txt

See https://github.com/python/typeshed/pull/9800 for context

Blacklist `distutils.dist.Distribution.announce`

---

stubdefaulter/stdlib-blacklist.txt

This is no longer necessary following https://github.com/python/typeshed/pull/9795: stubtest now passes for typeshed's `setuptools` stubs even if the correct default parameter is added to the stdlib stub for `distutils.dist.Distribution.announce`

Remove `distutils.dist.Distribution.announce` from the blacklist

---

pyproject.toml
stubdefaulter/__init__.py
test_stubdefaulter.py

This required a little bit of refactoring -- I had to introduce a new `ReplaceEllipsesUsingRuntime._infer_value_for_default` method, so that I had a method I could call recursively.
I've checked locally, and the changes `stubdefaulter` would make to typeshed's stdlib with this PR applied pass both mypy and flake8-pyi.

Add container defaults

---

stubdefaulter/__init__.py

We want to integrate `stubdefaulter` to `django-stubs`: https://github.com/typeddjango/django-stubs/pull/2327
Later we also want to add `stubdefaulter` to our CI, so it can check that no missing defaults are added. 
`--check` would help us to fail the CI. We would use both `--exit-zero` and `--check`, because there would be errors when importing django modules, we can't fix it from our side. So, we need them both to work correctly. Errors will be ignored with `--exit-zero` while `--check` will return `2` if there are any new changes.

Add `--check` argument for CI
